<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="6.2.0" />
  </ItemGroup>
	<ItemGroup>
		<ProjectReference Include="../Domain/Domain.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Features\Delete\" />
	  <Folder Include="Features\List\" />
	  <Folder Include="Features\Read\" />
	  <Folder Include="Features\Update\" />
	</ItemGroup>
</Project>
